import numpy as np
import os
import pandas as pd

class ProcessedDataLoader:
    def __init__(self, processed_dir='processed'):
        """
        Reads pre-processed .npy files generated by preprocess.py
        """
        self.processed_dir = processed_dir

    def load(self, dataset_name, entity_name, mode='train'):
        """
        Loads a specific entity file.
        mode: 'train', 'test', or 'labels'
        """
        # Construct path: processed/SMD/machine-1-1_train.npy
        filename = f"{entity_name}_{mode}.npy"
        path = os.path.join(self.processed_dir, dataset_name, filename)
        
        if not os.path.exists(path):
            raise FileNotFoundError(f"File not found: {path}")
            
        data = np.load(path)
        
        # Ensure 2D shape (Time, Feats)
        if len(data.shape) == 1:
            data = data.reshape(-1, 1)
            
        return data

    def get_available_entities(self, dataset_name):
        """
        Scans the folder to find all available entities automatically.
        """
        dataset_path = os.path.join(self.processed_dir, dataset_name)
        if not os.path.exists(dataset_path):
            return []
            
        files = os.listdir(dataset_path)
        entities = set()
        for f in files:
            if f.endswith('_train.npy'):
                # machine-1-1_train.npy -> machine-1-1
                entity = f.replace('_train.npy', '')
                entities.add(entity)
        
        return sorted(list(entities))

    @staticmethod
    def filter_low_variance(train, test, threshold=1e-4):
        """
        Filters out features with variance lower than threshold in the training set.
        Applies the same filter to the test set.
        """
        # Calculate variance along time axis (axis 0)
        train_var = np.var(train, axis=0)
        
        # Keep features with variance > threshold
        keep_indices = np.where(train_var > threshold)[0]
        
        if len(keep_indices) < train.shape[1]:
            # print(f"   > Filtering low-variance features: {train.shape[1]} -> {len(keep_indices)}")
            train_filtered = train[:, keep_indices]
            test_filtered = test[:, keep_indices]
            return train_filtered, test_filtered, keep_indices
        
        return train, test, np.arange(train.shape[1])

class PeriodicityCalculator:
    """
    Calculates Periodicity Weights (PW) for OmniTransfer.
    This logic remains separate from preprocessing as it is model-specific.
    """
    def __init__(self, alpha=1.0):
        self.alpha = alpha

    def calculate_cmnd(self, metric_series, max_tau=1440):
        # Optimized CMND calculation
        if len(metric_series) < 50 or np.var(metric_series) < 1e-5:
            return 0.0 
            
        # Downsample for speed if needed
        if len(metric_series) > 5000: 
            metric_series = metric_series[:5000]
        
        min_cmnd = float('inf')
        d_cumulative = 0
        
        # Sparse search for speed
        taus = range(1, min(len(metric_series)//2, max_tau), 5)
        
        for tau in taus:
            u = metric_series[:-tau]
            v = metric_series[tau:]
            d_tau = np.sum((u - v)**2)
            d_cumulative += d_tau
            
            avg_d = d_cumulative / len(range(1, tau+1, 5))
            if avg_d == 0: val = 1.0
            else: val = d_tau / avg_d
            
            if val < min_cmnd: min_cmnd = val
            
        return min_cmnd

    def compute_weights(self, mts_data):
        M = mts_data.shape[1]
        P = np.zeros(M)
        # print(f"   > Calculating Periodicity Weights for {M} metrics...")
        for j in range(M):
            P[j] = self.calculate_cmnd(mts_data[:, j])
        return np.power(P + 1e-6, -self.alpha)